manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/fliano
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: pmw3610
      import: app/west.yml
  self:
    path: config
